//! `SeaORM` Entity, @generated by sea-orm-codegen 1.1.10

use crate::entities::prelude::Password;
use sea_orm::entity::prelude::*;
use sea_orm::FromQueryResult;

#[derive(Clone, Debug, PartialEq, DeriveEntityModel, Eq)]
#[sea_orm(table_name = "password")]
pub struct Model {
    #[sea_orm(primary_key)]
    pub id: i64,
    pub master: String,
    pub name: String,
    pub website: String,
    pub username: String,
    pub email: String,
    pub encrypted_password: String,
    pub notes: String,
}

#[derive(DerivePartialModel, FromQueryResult, serde::Serialize, serde::Deserialize)]
#[sea_orm(entity = "Password")]
pub struct PartialModel {
    pub id: i64,
    pub name: String,
    pub website: String,
    pub username: String,
    pub email: String,
    pub notes: String
}

#[derive(DerivePartialModel, FromQueryResult, serde::Serialize, serde::Deserialize)]
#[sea_orm(entity = "Password")]
pub struct ItemPartialModel {
    pub name: String,
    pub website: String,
    pub username: String,
    pub email: String,
    pub encrypted_password: String,
    pub notes: String,
}

#[derive(Copy, Clone, Debug, EnumIter, DeriveRelation)]
pub enum Relation {}

impl ActiveModelBehavior for ActiveModel {}
