//! `SeaORM` Entity, @generated by sea-orm-codegen 1.1.10

use crate::entities::prelude::Master;
use sea_orm::entity::prelude::*;
use sea_orm::FromQueryResult;

#[derive(Clone, Debug, PartialEq, DeriveEntityModel, Eq)]
#[sea_orm(table_name = "master")]
pub struct Model {
    #[sea_orm(primary_key)]
    pub id: i32,
    #[sea_orm(unique)]
    pub username: String,
    pub hashed_password: String,
    pub master_salt: String,
}

#[derive(DerivePartialModel, FromQueryResult, serde::Serialize, serde::Deserialize)]
#[sea_orm(entity = "Master")]
pub struct PartialModel {
    pub id: i32,
    pub username: String,
}

#[derive(Copy, Clone, Debug, EnumIter, DeriveRelation)]
pub enum Relation {}

impl ActiveModelBehavior for ActiveModel {}
